### PR TITLE
Add option to update content as minor edit and include edit message

### PR DESCRIPTION
**Pull request by Battleroid**
Hey there. I've added a couple minor options to `update_content`. The ability to specify the update as a minor edit `minor_edit=True`, as well as optionally including a message about the version change, e.g. `edit_message='Updated at ...'`.

I've tested this with our instance and it (thankfully) doesn't notify anyone on update, and naturally the message is included as well.

screen shot 2018-04-25 at 1 46 42 pm

Also, thanks a bunch for this library, it's been saving me quite a bit of time.

### CODE REVIEW

**Comment by DaveTCode** [comment]
Great, thanks for that. I'll just add a couple of integration tests around it and get a new version pushed out tonight

**Comment by Battleroid** [comment]
Cool beans, thanks!

**Comment by DaveTCode** [comment]
Hmm, actually having added a test for this I've found that the minorEdit field is set to False on the JSON response of the update message which included minorEdit=true. 

I'm 80% confident that the API is just being daft and doesn't return minorEdit because Confluence doesn't actually know any more after a version has been created but how sure are you that it works? If so I'll just comment the bad API in the test and call it done

**Comment by Battleroid** [comment]
Lemme toy with it a bit more and confirm.

**Comment by Battleroid** [comment]
Looks like it is retaining it as an unpublished change, odd, not sure why. What's worse, is after you push a minor edit, any edits afterward do not change the draft status.

Tried specifying the content status as current in edits, continues to remain as a draft regardless of the status and minor edit status.

**Comment by Battleroid** [comment]
Also appears that before (and after) updating the content, the page indicates the status is set to current, however in the UI it warns it contains unpublished changes.

**Comment by Battleroid** [comment]
Looks like it works though, it complains there's unpublished changes, but in the UI it is published with the most recent changes I've pushed through with minorEdit=true + setting the current status.

**Pull request merged**
